### PR TITLE
Fix missing jobType label in the metrics

### LINKED ISSUE #421: Prometheus jobType label missing
## Describe the bug

The `jobType` label is missing in the metrics.

## Additional context

* Migrated issue from https://github.com/appuio/charts/issues/286
* Before the migration to Operator SDK, the label "jobType" was present in the Operator metrics.

## Logs

If applicable, add logs to help explain your problem.
```console
# HELP k8up_jobs_failed_counter The total number of backups that failed
# TYPE k8up_jobs_failed_counter counter
k8up_jobs_failed_counter{namespace="drupal-example-test1-master"} 3
```

## Expected behavior
```console
k8up_jobs_failed_counter{namespace="drupal-example-test1-master",jobType="backup"} 3
```

## To Reproduce

* https://github.com/vshn/k8up/blob/master/observer/observer.go#L35
* https://github.com/vshn/k8up/blob/master/observer/observer.go#L31 (no job type passed via parameter)

## Environment (please complete the following information):

- Image Version: v1.0.4
- K8s Version: irrelevant
- K8s Distribution: irrelevant

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

* Fixes #421 

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`,
      as they show up in the changelog
- [ ] Update tests.
- [x] Link this PR to related issues.

### CODE REVIEW

**Comment by ccremer** [comment]
After running the e2e-tests, these are the relevant K8up metrics:
```console
# HELP k8up_jobs_queued_gauge How many jobs are currently queued up
# TYPE k8up_jobs_queued_gauge gauge
k8up_jobs_queued_gauge{jobType="backup",namespace="k8up-e2e-subject"} 0
k8up_jobs_queued_gauge{jobType="restore",namespace="k8up-e2e-subject"} 0
# HELP k8up_jobs_successful_counter The total number of backups that went through cleanly
# TYPE k8up_jobs_successful_counter counter
k8up_jobs_successful_counter{jobType="schedule",namespace="k8up-e2e-subject"} 4
# HELP k8up_jobs_total The total amount of all jobs run
# TYPE k8up_jobs_total counter
k8up_jobs_total{jobType="schedule",namespace="k8up-e2e-subject"} 4
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
```
Is it just me, or do I miss the `k8up_jobs_successful_counter{jobType="backup",namespace=...}` ?

@Kidswiss Would you expect succeeded counter to go up as well if the Backup didn't come from a Schedule?

```console
2021-04-14T12:11:51.251Z DEBUG controllers.Backup adding job to the queue {"backup": "k8up-e2e-subject/k8up-k8up-backup"}
2021-04-14T12:11:51.831Z INFO controllers.Backup Listing all PVCs {"backup": "k8up-e2e-subject/k8up-k8up-backup", "annotation": "k8up.syn.tools/backup", "namespace": "k8up-e2e-subject"}
2021-04-14T12:11:51.931Z INFO controllers.Backup PVC doesn't have annotation, adding to list {"backup": "k8up-e2e-subject/k8up-k8up-backup", "namespace": "k8up-e2e-subject", "name": "subject-pvc"}
2021-04-14T12:11:51.934Z INFO observer new event on observed job {"event": "create", "jobName": "k8up-e2e-subject/k8up-k8up-backup"}
2021-04-14T12:11:51.953Z INFO observer new event on observed job {"event": "running", "jobName": "k8up-e2e-subject/k8up-k8up-backup"}
2021-04-14T12:11:51.961Z INFO observer new event on observed job {"event": "running", "jobName": "k8up-e2e-subject/k8up-k8up-backup"}
2021-04-14T12:12:03.506Z INFO observer new event on observed job {"event": "suceeded", "jobName": "k8up-e2e-subject/k8up-k8up-backup"}
2021-04-14T12:12:03.506Z INFO observer job succeeded {"jobName": "k8up-e2e-subject/k8up-k8up-backup"}
2021-04-14T12:12:16.778Z INFO observer new event on observed job {"event": "delete", "jobName": "k8up-e2e-subject/k8up-k8up-backup"}
2021-04-14T12:12:16.778Z INFO observer deleting job from observer {"jobName": "k8up-e2e-subject/k8up-k8up-backup"}
```

**Comment by Kidswiss** [comment]
> @Kidswiss Would you expect succeeded counter to go up as well if the Backup didn't come from a Schedule?

Yeah I would expect that, too. From your snipped it looks like it only increments for scheduled jobs right now?

**Comment by ccremer** [comment]
> Yeah I would expect that, too. From your snipped it looks like it only increments for scheduled jobs right now?

I've found another small bug while investigating this: https://github.com/vshn/k8up/blob/master/controllers/job_controller.go#L43
The job obj is called with nil, since it's not known from a job controller which type it is. So eventually it defaults to "schedule", that's why.

Now that we also have a label on Jobs identifying which type it is, we could use that.

**Comment by ccremer** [comment]
Now it looks better:
```console
# HELP k8up_jobs_queued_gauge How many jobs are currently queued up
# TYPE k8up_jobs_queued_gauge gauge
k8up_jobs_queued_gauge{jobType="backup",namespace="k8up-e2e-subject"} 0
k8up_jobs_queued_gauge{jobType="restore",namespace="k8up-e2e-subject"} 0
# HELP k8up_jobs_successful_counter The total number of jobs that went through cleanly
# TYPE k8up_jobs_successful_counter counter
k8up_jobs_successful_counter{jobType="backup",namespace="k8up-e2e-subject"} 2
k8up_jobs_successful_counter{jobType="restore",namespace="k8up-e2e-subject"} 1
# HELP k8up_jobs_total The total amount of all jobs run
# TYPE k8up_jobs_total counter
k8up_jobs_total{jobType="backup",namespace="k8up-e2e-subject"} 2
k8up_jobs_total{jobType="restore",namespace="k8up-e2e-subject"} 1
```

**Review by Kidswiss — APPROVED** [review]
LGTM now

**Pull request merged**
