### PR TITLE
Setup CodeClimate

### PR DESCRIPTION
**Pull request by cimnine**
## Todo

- [ ] Decide whether `go lint` should be kept enabled
- [x] Hook Repository Up With codeclimate.com
- [x] Report Test Coverage to codeclimate

## Related Links

- https://docs.codeclimate.com/docs/github-pull-requests
- https://github.com/marketplace/actions/code-climate-coverage-action

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [ ] ~Update the documentation.~
- [ ] ~Update tests.~
- [x] Link this PR to related issues.

### CODE REVIEW

**Comment by cimnine** [comment]
There's one feature in this PR to discuss: `go lint`

Shall I remove it from the code climate static analysis report or are we committing to follow its suggestions in the future – at least, where they make sense?

**Comment by ccremer** [comment]
Can we somehow ignore the current issues?

Also, I noticed that the integration tests are not currently run just `make test`, but there's an `make integration_test` target. That should increase coverage

**Comment by cimnine** [comment]
> Can we somehow ignore the current issues?

No. But they won't show up as blocker in further PRs, because codeclimate only reports the _new_ issues. And since this time _all are new_, it reports them all.

> Also, I noticed that the integration tests are not currently run just make test, but there's an make integration_test target. That should increase coverage

I suggest to look at this in a separate issue.

**Review by ccremer — APPROVED** [review]
lgtm

**Pull request merged**
