### PR TITLE
 feat(prune): rewrite prune controller

### LINKED ISSUE #125: Add Prune jobs to the rewrite
Add the check job logic to the new implementation: https://github.com/vshn/k8up/tree/master/service/prune

The controller is already implemented for that. Now we need to implement an Executor that actually triggers the job.

That one should be quite trivial to implement.

With #114 merged the new implementation lives on the development branch.

### PR DESCRIPTION
**Pull request by mweibel**
fixes #125

related: #130

### CODE REVIEW

**Comment by mweibel** [comment]
@Kidswiss I rebased & removed the goroutine - please review.

**Comment by tobru** [comment]
@mweibel This needs a conflict cleanup.

**Comment by mweibel** [comment]
@tobru thanks for the info - done.

**Comment by tobru** [comment]
@mweibel I suggest to merge this one and continue with improvements later on - starting from the development branch. OK?

**Comment by mweibel** [comment]
👍 I'll quickly fix the conflict again :)

**Comment by tobru** [comment]
Already done =)

**Comment by mweibel** [comment]
ah, or like that 👍 thanks

**Pull request merged**
