### PR TITLE
Print Schedule ref and status conditions in kubectl

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

- Displays the name of the schedule if a job got created by a schedule, otherwise it's empty
- Displays the reason for a completion condition if there is any
- For Backups, it also displays the status condition of prebackups

```console
$ k get backup
NAME                         SCHEDULE REF    COMPLETION   PREBACKUP              AGE
schedule-test-backup-4fpbd   schedule-test   Failed       NoPreBackupPodsFound   3m20s
schedule-test-backup-b6bxz   schedule-test                NoPreBackupPodsFound   20s
schedule-test-backup-sj5rt   schedule-test                NoPreBackupPodsFound   80s
schedule-test-backup-whnkl   schedule-test   Failed       NoPreBackupPodsFound   2m20s
```

## Checklist
- [x] Keep pull requests small so they can be easily reviewed.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`,
      as they show up in the changelog
- [x] Update the documentation.
- [x] ~Update tests.~
- [x] ~Link this PR to related issues.~

### CODE REVIEW

**Review by cimnine — APPROVED** [review]
Is the _SCHEDULE REF_ empty, if there is no owner resource, i.e. if the resource was created manually (not via Schedule)?

**Comment by ccremer** [comment]
> Is the _SCHEDULE REF_ empty, if there is no owner resource, i.e. if the resource was created manually (not via Schedule)?

correct, it display an empty string on nonexistent properties.

**Review by cimnine — APPROVED** [review]
LGTM, but it would we cool to highlight this feature in https://k8up.io/k8up/1.0.0/how-tos/check-status.html .

**Comment by ccremer** [comment]
> LGTM, but it would we cool to highlight this feature in https://k8up.io/k8up/1.0.0/how-tos/check-status.html .

uh actually that page doesn't show the new status and conditions yet. (in kubectl describe ...) Can you recreate your backup demo and update the page? or should I attempt manually?

**Comment by cimnine** [comment]
> Can you recreate your backup demo and update the page?

Long Answer: I believe I've manually adjusted the pod's names from whatever resources I tested my PR with at that time.
Short Answer: No, not really 😔

**Comment by ccremer** [comment]
I tried something. WDYT?

**Review by tobru — APPROVED** [review]
Documentation LGTM

**Pull request merged**
