### PR TITLE
Add missing finalizer RBAC rules

### LINKED ISSUE #379: OpenShift 3.11 missing RBAC for jobs/finalizers
## Describe the bug

When deploying to OpenShift 3.11 we found that the operator can't create the jobs. We found following errors on the backup objects:
```
status:
    conditions:
    - lastTransitionTime: "2021-02-22T20:24:30Z"
      message: The resource is ready
      reason: Succeeded
      status: "True"
      type: PreBackupPodsReady
    - lastTransitionTime: "2021-02-22T20:24:07Z"
      message: 'unable to create  ''namespace/backup-schedule-backup-mmnr4'':
        jobs.batch "backup-schedule-backup-mmnr4" is forbidden: cannot set blockOwnerDeletion
        if an ownerReference refers to a resource you can''t set finalizers on: no
        RBAC policy matched, <nil>'
      reason: CreationFailed
      status: "False"
      type: Ready
```

It seems that the operator can't update finalizers on job objects. We adjusted the RBAC as follows (https://github.com/vshn/k8up/blob/master/config/rbac/role.yaml):
```
- apiGroups:
  - batch
  resources:
  - jobs
  - jobs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

Which seemed to help.

Found some more instances where the permissions are needed: for backup `backup` objects. I'd suggest to go through the code and add the finalizer permissions accordingly for object where we use it.

## Additional context

Seems only to happen on 3.11 as we have other deployments on k8s that don't suffer this issue.

## Expected behavior

K8up can create jobs on OpenShift 3.11 without issues.

## To Reproduce

1. Install k8up via helmfile on OpenShift 3.11
2. Run a backup
3. The job won't be created and k8up will retry every 30 seconds (as expected)

## Environment (please complete the following information):

- Image Version: v1.0
- K8s Version: 1.11
- K8s Distribution: OpenShift 3.11

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

* Fixes #379 
* Also see https://sdk.operatorframework.io/docs/faqs/

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`,
      as they show up in the changelog
- [x] Link this PR to related issues.

### CODE REVIEW

**Comment by tobru** [comment]
@Kidswiss Would you mind giving that one a review?

**Comment by Kidswiss** [comment]
I amended #379 a bit yesterday.

Looks like other finalizers are also missing. At least for the backup object it also needs the finalizer RBAC. I added it the finalizer RBAC to all CRDs as well, but we need to check what CRDs actually use finalizers and amend accordingly.

Also I feel like we need some automated testing for 3.11 clusters, too. We still maintain quite a lot of those with k8up...

**Comment by ccremer** [comment]
> Also I feel like we need some automated testing for 3.11 clusters, too. We still maintain quite a lot of those with k8up...

We [are already testing e2e-testing for K8s 1.13](https://github.com/vshn/k8up/blob/master/.github/workflows/e2e.yml#L16). But we lack actual test cases, the first test is #372

**Comment by Kidswiss** [comment]
Is that just a 1.13 K8s cluster or an actual OpenShift? I assume the finalizer RBAC stuff is OpenShift specific because we haven't encountered it before...

**Comment by ccremer** [comment]
Unfortunately, K8s 1.13 is the closest we can get to OpenShift 3.11. It's just so horribly old it's nowhere supported with tooling anymore.

**Comment by ccremer** [comment]
@Kidswiss can you re-review?

**Comment by Kidswiss** [comment]
The we should get rid of the OS 3.11 clusters ASAP :D

**Review by Kidswiss — APPROVED** [review]
LGTM

**Pull request merged**
