### PR TITLE
feat: rewrite check executor

### LINKED ISSUE #123: Add Check jobs to the rewrite
Add the check job logic to the new implementation: https://github.com/vshn/k8up/tree/master/service/check

The controller is already implemented for that. Now we need to implement an Executor that actually triggers the job.

That one should be quite trivial to implement.

With #114 merged the new implementation lives on the `development` branch.

### PR DESCRIPTION
**Pull request by susana-garcia**
Reopen PR:

fixes #123 

related: #132

### CODE REVIEW

**Comment by Kidswiss** [comment]
The check loses the `RESTIC_PASSWORD` env var after `vars.Merge()`. Haven't digged in too deep to analyse why. But that part is basically identical to the other jobs...

@mweibel we want to change the whole env handling anyways. Do you think we should invest much time here to debug?

**Comment by mweibel** [comment]
maybe we should add a (failiing) test similar to what I did in #140 and merge it then? making it pass when we rewrite the env stuff?

**Comment by Kidswiss** [comment]
Sounds good to me. In that case I approve the PR.

**Review by Kidswiss — APPROVED** [review]

**Comment by susana-garcia** [comment]
@Kidswiss I've read the comments in #140 and I assumed we'll merge first the open PRs, fix the envVar merging and add better tests later on as discussed initially (as the ones in #140 are not solving the problem of losing values).

**Pull request merged**
