### PR TITLE
Document k8up annotations

### PR DESCRIPTION
**Pull request by cimnine**
## Summary

Adds a section for the _Annotations_ that influence K8up. I've written it down, since I was looking it up and did not find a complete and concise reference in the docs.

Also, I've applied `go mod tidy`.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`,
      as they show up in the changelog
- [x] Update the documentation.
- [x] Update tests.
- [x] Link this PR to related issues.

### CODE REVIEW

**Review by tobru — APPROVED** [review]

**Review by tobru — CHANGES_REQUESTED** [review]
Page needs to be added to the navigation in the `partials/` directory. You can check the documentation by running `make docs-preview`,

**Comment by cimnine** [comment]
> Page needs to be added to the navigation in the `partials/` directory. You can check the documentation by running `make docs-preview`.

I've had it there for a brief moment. But somehow I didn't commit it.

**Review by tobru — APPROVED** [review]
Why is the file `go.sum` part of this PR? What does this do?

**Comment by cimnine** [comment]
> Why is the file go.sum part of this PR? What does this do?

It's not actually related. But I thought to open a PR for it seperatly would have been too much. It's just cleaning out references to the go modules that are no longer in use, i.e. the result of `go mod tidy`.

**Review by ccremer — APPROVED** [review]

**Pull request merged**
