### PR TITLE
Update Go to v1.16

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

Update to Go runtime 1.16

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`,
      as they show up in the changelog

### CODE REVIEW

**Comment by ccremer** [comment]
ready to update yet?

**Comment by cimnine** [comment]
Go 1.16 is not yet available on the Mac via Homebrew (see Homebrew/homebrew-core/pull/71289), but I believe this to be a matter of days or even hours.

**Review by cimnine — APPROVED** [review]

**Comment by ccremer** [comment]
let's wait for it then ;)

**Comment by cimnine** [comment]
It's merged and available.

**Pull request merged**
