### PR TITLE
Generate API reference documentation with generator

### LINKED ISSUE #210: Automatically Generate CRD Docs in Asciidoc for Antora
## Summary

**As** developer
**I want** to have automatically generated CRD documentation
**So that** documentation about CRDs is always automatically up-to-date

## Context

Currently the CRDs are manually documented in `docs/`. In Project Syn Lieutenant Operator we found a way to [automatically generate](https://github.com/projectsyn/lieutenant-operator/blob/master/create-api-docs.sh) this documentation. This should be ported to K8up.

## Further links

* https://github.com/projectsyn/lieutenant-operator/blob/master/create-api-docs.sh
* https://docs.syn.tools/lieutenant-operator/references/crds-html.html

## Acceptance criteria

CRD documentation is automatically generated in Asciidoc format.

## Implementation Ideas

Get inspiration for the work done in https://github.com/projectsyn/lieutenant-operator and port it over here.

### PR DESCRIPTION
**Pull request by cimnine**
## Summary

This is an attempt to resolve #210 

* Uses https://github.com/elastic/crd-ref-docs to generate AsciiDoctor file
* Template is copied from https://github.com/elastic/crd-ref-docs/tree/master/templates/asciidoctor, but section/titles are altered somewhat.
* Integrated into `make generate`
* Integrated into `go.mod` for Renovate support
* Initially inspired by using the script from [lieutenant-operator](https://github.com/projectsyn/lieutenant-operator/blob/12fcea1575ed7c892daa72409335d7c4daf2a3f0/create-api-docs.sh), but it proved to be kaputt.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`,
      as they show up in the changelog
- [x] Update the documentation.
- [x] ~Update tests.~
- [x] Link this PR to related issues.

### CODE REVIEW

**Comment by cimnine** [comment]
Currently, the state looks like this:

```
I0205 17:10:25.510900   96698 main.go:129] parsing go packages in directory api/v1alpha1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140ebb5]

goroutine 1 [running]:
k8s.io/gengo/parser.(*Builder).AddDirRecursive(0xc00007f630, 0x7ffeefbff66f, 0xc, 0x59, 0xad)
	/Users/cimnine/src/vshn/k8up/docs/tempgopath/pkg/mod/k8s.io/gengo@v0.0.0-20201203183100-97869a43a9d9/parser/parse.go:234 +0xb5
main.parseAPIPackages(0x7ffeefbff66f, 0xc, 0x150510f, 0x23, 0xc00018ff30, 0x1, 0x1)
	/Users/cimnine/src/vshn/k8up/docs/tempgopath/pkg/mod/github.com/ahmetb/gen-crd-api-reference-docs@v0.3.0/main.go:203 +0x65
main.main()
	/Users/cimnine/src/vshn/k8up/docs/tempgopath/pkg/mod/github.com/ahmetb/gen-crd-api-reference-docs@v0.3.0/main.go:130 +0x2d4
```

**Comment by tobru** [comment]
This problem might be related to https://github.com/ahmetb/gen-crd-api-reference-docs/issues/12. Does that ring a bell @ccremer?

**Comment by tobru** [comment]
I replaced the script to be mostly the same as the one from lieutenant-operator. It looks better, but still no luck:

```
[...]
+ go run github.com/ahmetb/gen-crd-api-reference-docs -config ./docs/gen-api.json -api-dir ./api/v1alpha1 -template-dir ./docs/template -out-file ./docs/modules/ROOT/partials/crds.html -v=4
I0209 09:40:36.995711 1335045 main.go:129] parsing go packages in directory ./api/v1alpha1
I0209 09:40:47.543486 1335045 main.go:213] trying package=func (*k8s.io/apimachinery/pkg/apis/meta/v1.Condition).DeepCopyInto(out *k8s.io/apimachinery/pkg/apis/meta/v1 groupName=
I0209 09:40:47.543527 1335045 main.go:213] trying package=func (*k8s.io/api/core/v1.Handler).XXX_Merge(src github.com/gogo/protobuf/proto groupName=
[...]
I0209 09:40:47.552584 1335045 main.go:213] trying package=func (k8s.io/apimachinery/pkg/api/resource.infDecAmount).AsScale(scale k8s.io/apimachinery/pkg/api/resource.Scale) (k8s.io/apimachinery/pkg/api/resource groupName=
I0209 09:40:47.552590 1335045 main.go:213] trying package=func (k8s.io/apimachinery/pkg/runtime.Object).GetObjectKind() k8s.io/apimachinery/pkg/runtime/schema groupName=
I0209 09:40:47.552594 1335045 main.go:213] trying package=func (regexp.lazyFlag).match(op regexp/syntax groupName=
F0209 09:40:47.552605 1335045 main.go:135] no API packages found in ./api/v1alpha1
```

This is something I'm not able to figure out why. The only thing I see is different to other projects successfully using `gen-crd-api-reference-docs` is that the directory structure is different. For example Lieutenant Operators stores it's API structs under `pkg/apis/syn/v1alpha1/*_types.go` whereas K8up stores it under `api/v1alpha1/*_types.go`. Not sure if this could be the reason for "no API packages found".

**Comment by ccremer** [comment]
Made it work by using another tool instead :)

**Comment by ccremer** [comment]
@tobru you're invited to review the documentation and the template

**Comment by tobru** [comment]
Very cool! Thanks a lot. I did a small adjustment and IMHO that's done with that.

**Review by tobru — APPROVED** [review]

**Comment by tobru** [comment]
> Strange. The CRD doc generator here only detects 2 CRDs: https://doc.crds.dev/github.com/vshn/k8up@v1.0.0-rc6

W00t! Just ping https://twitter.com/hasheddan/, he's very helpful. Or open an issue in https://github.com/crdsdev/doc

**Comment by ccremer** [comment]
I think there is already:
https://github.com/crdsdev/doc/issues/126

**Comment by ccremer** [comment]
Merging this. The bug in the generator site is not something that holds us back since we have our own reference now, and fixes we can apply later as well.

**Pull request merged**
