### PR TITLE
feat: rewrite archive

### LINKED ISSUE #124: Add Archive jobs to the rewrite
Add the check job logic to the new implementation: https://github.com/vshn/k8up/tree/master/service/archive

The controller is already implemented for that. Now we need to implement an Executor that actually triggers the job.

With #114 merged the new implementation lives on the development branch.

### PR DESCRIPTION
**Pull request by susana-garcia**
fixes #124

### CODE REVIEW

**Comment by susana-garcia** [comment]
@Kidswiss can you have a look at this PR when you a minute, please? I'm not entirely happy with it, so I'd really appreciate your feedback

**Comment by Kidswiss** [comment]
Haven't tested it yet, but looks more or less like the other job implementations. I think the parts you're not happy about are the same that Michael already mentioned, correct?

**Comment by susana-garcia** [comment]
@Kidswiss not really, the parts I'm not that happy with are more the parts I added from the other branch that I'm not sure if that was needed. For example: `BuildTagArgs` or the `setupEnvVars`

**Comment by Kidswiss** [comment]
I actually assume that the tag handling got lost while I implemented the `backup` case. So it should be there actually. I'd even say it should be already handled in the `GetGenericJob()` method as all the jobs can accept a list of tags.

As for the envVars: It looks good, but looking through the code I found an issue.  Archive (and restore for that matter) may need two sets of S3 credentials:
1. for the backup location
2. for the restore location

You only call `RestoreMethod.S3.EnvVars()` so that will only create the one set of the S3 credentials. But the bigger issue I found is that `RestoreMethod.S3.EnvVars()` will produced the same set of envVars as `Backend.S3.EnvVars()` would. Which would overwrite the other set. `RestoreMethod.S3.EnvVars()` should create envVars named like:

```
RESTORE_S3ENDPOINT
RESTORE_ACCESSKEYID
RESTORE_SECRETACCESSKEY
RESTORE_DIR # this one would be used for the restore/archive restoreMethod folder
```

See https://github.com/vshn/wrestic/blob/master/restic/restic.go#L37
and for the restore method: https://github.com/vshn/k8up/blob/master/apis/backup/v1alpha1/restore.go#L36

So it needs to check if the restore method is folder or s3. If it's S3 set above envVars.

I hope it's somewhat clear what I'm trying to say :) if not we can do a zoom call.

**Review by Kidswiss — APPROVED** [review]
Looks good, the ugly things will be looked at once we have a complete picture of the jobs and their ugliness.

Tested it and the produced jobs looks fine.

**Pull request merged**
