### PR TITLE
Docs: fix typo readme

### PR DESCRIPTION
**Pull request by susana-garcia**

### CODE REVIEW

**Review by Kidswiss — APPROVED** [review]

**Review by ccremer — APPROVED** [review]
Could you reword your commit with a `Docs: ` prefix? That way it won't be visible in the auto-generated changelog. I don't think this is worth mentioning ;)

**Comment by Kidswiss** [comment]
@ccremer Are there some docs about the automatic changelog generator? Like, are there other prefixes that control its behaviour?

**Comment by ccremer** [comment]
@Kidswiss our filters are here: https://github.com/vshn/k8up/blob/master/.goreleaser.yml#L27
In general, it's documented here: https://goreleaser.com/customization/release/#customize-the-changelog

**Comment by Kidswiss** [comment]
Ah so that's also goreleaser magic, nice! Really need to read into that thing. Thanks!

**Comment by susana-garcia** [comment]
@Kidswiss  that makes two of us :)

**Pull request merged**
